### ISSUE TITLE
Presets should support multiple chemistries

### ISSUE THREAD

**Issue by fhriley** [fhriley/bumpemu#2]
Something like this:

```
lipo:
  accurate: 1
  normal: 2
  fastest: 3
  storage: 7
  discharge: 2
  analyze: 1
  monitor: 1
pb:
  ...
```

Then pick the correct preset based on the battery file provided.
